DROP TABLE IF EXISTS t_scores;
DROP TABLE IF EXISTS t_player;
DROP TABLE IF EXISTS t_games;

CREATE TABLE t_player (
    pk_player TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pseudo VARCHAR(50) NOT NULL,
    PRIMARY KEY (pk_player)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE t_games (
    pk_game TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (pk_game)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE t_scores (
    pk_score INT UNSIGNED NOT NULL AUTO_INCREMENT,
    score INT NOT NULL,
    fk_player TINYINT UNSIGNED NOT NULL,
    fk_game TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (pk_score),
    FOREIGN KEY (fk_player) REFERENCES t_player(pk_player) ON DELETE CASCADE,
    FOREIGN KEY (fk_game) REFERENCES t_games(pk_game) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
